export interface Config {
  /**
   * Your project name.
   */
  name: string;
  /**
   * Debug mode: show app backend logs.
   */
  debug?: boolean;
  /**
   * Do not open ngxe in browser on the start.
   */
  notOpen?: boolean;
  /**
   * Path to json file generated by extract-i18n command.
   */
  input: string;
  /**
   * Files generated by the tool.
   */
  output: {
    /**
     * Path to json file with source messages sorted by keys.
     */
    source: string;
    translations: {
      /**
       * Locale name.
       */
      locale: string;
      /**
       * Path to json file with target messages sorted by keys.
       */
      path: string;
    }[];
  };
}
