name: Demo deploy

on:
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Build
        run: |
          npm i
          npm run ngxe:build:demo
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      -
        name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: dist/ngxe
          fqdn: ngxe.oleksanovyk.com
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
