name: Publish

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build
        run: |
          npm i
          npm run test -- --watch=false --browsers=ChromeHeadless
          npm run release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
